#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# GPG
source $HOME/.gpg-profile

# Bind search backward
bindkey -M viins '^r' history-incremental-pattern-search-backward
bindkey -M vicmd '^r' history-incremental-pattern-search-backward

# History Configuration
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
setopt share_history # share history between different instances of the shell

# HSTR configuration 
alias hh=hstr                    # hh to be alias for hstr
export HISTFILE=~/.zsh_history  # ensure history file visibility
export HSTR_CONFIG=hicolor        # get more colors
bindkey -s "\C-r" "\eqhstr --\n" # bind hstr to Ctrl-r (for Vi mode check doc)

# Kubectl
alias k=kubectl
alias ktx=kubectx
alias kns=kubens

# Kubectl prompt
zstyle ':vcs_info:git*' formats "%{$fg[grey]%}%s %{$reset_color%}%r/%S%{$fg[grey]%} %{$fg[blue]%}%b%{$reset_color%}%m%u%c%{$reset_color%} "
zstyle ':vcs_info:*' check-for-changes true
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
export PS1='%F{135}%n%f at %F{166}%m%f in %F{118}%~%f ${vcs_info_msg_0_} $(kube_ps1)
$python_info[virtualenv]${editor_info[keymap]} '

if [[ -s "${ZDOTDIR:-$HOME}/.zsh/general.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/general.zsh"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
